// proto/pdf_converter.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: pdf_converter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PDFConverter_Convert_FullMethodName = "/pdf.PDFConverter/Convert"
)

// PDFConverterClient is the client API for PDFConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PDFConverterClient interface {
	Convert(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PDFChunk, ConvertResponse], error)
}

type pDFConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewPDFConverterClient(cc grpc.ClientConnInterface) PDFConverterClient {
	return &pDFConverterClient{cc}
}

func (c *pDFConverterClient) Convert(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PDFChunk, ConvertResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PDFConverter_ServiceDesc.Streams[0], PDFConverter_Convert_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PDFChunk, ConvertResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PDFConverter_ConvertClient = grpc.ClientStreamingClient[PDFChunk, ConvertResponse]

// PDFConverterServer is the server API for PDFConverter service.
// All implementations must embed UnimplementedPDFConverterServer
// for forward compatibility.
type PDFConverterServer interface {
	Convert(grpc.ClientStreamingServer[PDFChunk, ConvertResponse]) error
	mustEmbedUnimplementedPDFConverterServer()
}

// UnimplementedPDFConverterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPDFConverterServer struct{}

func (UnimplementedPDFConverterServer) Convert(grpc.ClientStreamingServer[PDFChunk, ConvertResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Convert not implemented")
}
func (UnimplementedPDFConverterServer) mustEmbedUnimplementedPDFConverterServer() {}
func (UnimplementedPDFConverterServer) testEmbeddedByValue()                      {}

// UnsafePDFConverterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PDFConverterServer will
// result in compilation errors.
type UnsafePDFConverterServer interface {
	mustEmbedUnimplementedPDFConverterServer()
}

func RegisterPDFConverterServer(s grpc.ServiceRegistrar, srv PDFConverterServer) {
	// If the following call pancis, it indicates UnimplementedPDFConverterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PDFConverter_ServiceDesc, srv)
}

func _PDFConverter_Convert_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PDFConverterServer).Convert(&grpc.GenericServerStream[PDFChunk, ConvertResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PDFConverter_ConvertServer = grpc.ClientStreamingServer[PDFChunk, ConvertResponse]

// PDFConverter_ServiceDesc is the grpc.ServiceDesc for PDFConverter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PDFConverter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdf.PDFConverter",
	HandlerType: (*PDFConverterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Convert",
			Handler:       _PDFConverter_Convert_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pdf_converter.proto",
}
