# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/pdf_converter.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'proto/pdf_converter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/pdf_converter.proto\x12\x03pdf\"\x18\n\x08PDFChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1f\n\x0f\x43onvertResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2@\n\x0cPDFConverter\x12\x30\n\x07\x43onvert\x12\r.pdf.PDFChunk\x1a\x14.pdf.ConvertResponse(\x01\x42\nZ\x08./;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.pdf_converter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010./;proto'
  _globals['_PDFCHUNK']._serialized_start=34
  _globals['_PDFCHUNK']._serialized_end=58
  _globals['_CONVERTRESPONSE']._serialized_start=60
  _globals['_CONVERTRESPONSE']._serialized_end=91
  _globals['_PDFCONVERTER']._serialized_start=93
  _globals['_PDFCONVERTER']._serialized_end=157
# @@protoc_insertion_point(module_scope)
